### ISSUE TITLE
Regression bug with (possibly) TRT

### ISSUE THREAD

**Issue by ivan-w** [Fish-Git/hyperion#107]
c03d9d0819a03e694e25fcd300b4fdc0db5fe92e

Starting with this commit, VM/SP 5 CP is having problems parsing CP command arguments (per git bisect).

It *MAY* be possible the commit broke TRT in an obscure way.

Investigation in progress...

**Comment by ivan-w** [comment]
Before the commit : 
cp sp pun * cl a           
Ready; T=0.01/0.01 00:07:19
After the commit : 
cp sp pun * cl a                   
DMKCSP028E Class missing or invalid
Ready(00028); T=0.01/0.01 00:14:29 

Looking at DMKCSP - there is a call to DMKSCNSD (which fails) leading to the DMKCSP028E message - But the input might have been processed beforehand.. I *suspect* there is a call to TRT somewhere ;)

**Comment by Fish-Git** [comment]
(Dang!)

Then `MVCIN` instruction might be broken as well since it's using the same technique: using `'vfetchc'` to copy operand-2 data to a work area, processing it from there, and then `'vstorec'`ing the results back to operand-1 storage.

Do you think it might have anything to do with exception order/priority? That's one area I didn't pay very close attention on and one of the things my "CLCL-et-al" test`(*)` doesn't bother to test for.

Also, FYI: the version of the TRT code in commit c03d9d0819a03e694e25fcd300b4fdc0db5fe92e is _slightly different_ from the final version made in subsequent commit 92329434c062602bdf94c8fcf8b2a507eb605b19. (I decided to just fetch _all_ of operand-2 instead of only as much as might be needed (which is what I was doing before).) Does the problem also occur with commit 92329434c062602bdf94c8fcf8b2a507eb605b19 too?

In any case, _THANK YOU_ for reporting (and investigating) this, Ivan! If there's anything I can do to help, please let me know.
___
`(*)` [CLCL-et-al.tst](https://github.com/Fish-Git/hyperion/blob/master/tests/CLCL-et-al.tst), [CLCL-et-al.asm](https://github.com/Fish-Git/hyperion/blob/master/tests/CLCL-et-al.asm), [CLCL-et-al.list](https://github.com/Fish-Git/hyperion/blob/master/tests/CLCL-et-al.list), [CLCL-et-al.pdf](https://github.com/Fish-Git/hyperion/blob/master/tests/CLCL-et-al.pdf).

**Comment by ivan-w** [comment]
I suspect a very obscure (fence) problem that only occurs in very specific situations... I need to break down the changes introduced by the c03d9d0819a03e694e25fcd300b4fdc0db5fe92e commit... It has to apply to a very specific situation otherwise it would have been detected way earlier !

**Comment by Fish-Git** [comment]
> I suspect a very obscure (fence) problem...

Maybe we just need to insert a memory barrier before/after it?

**Comment by ivan-w** [comment]
Ah ah.. No I mean we may be off by 1 somewhere...
It's probably a very simple problem !

**Comment by Fish-Git** [comment]
> No I mean we may be off by 1 somewhere...

Ah. Okay. Sorry for the misunderstanding.

Well if that's your suspicion, then you might want to try commit 92329434c062602bdf94c8fcf8b2a507eb605b19 instead. In commit 92329434c062602bdf94c8fcf8b2a507eb605b19 I'm fetching the entirety of operand-2, whereas in commit c03d9d0819a03e694e25fcd300b4fdc0db5fe92e (the one you reported) I'm calculating and then fetching only as much of operand-2 as needed.

Unless of course I'm not processing all of operand-1? But if that were the case then my "CLCL-et-al" runtest test case _should_ have caught it, so I doubt it's that.

I wonder what it is?

Ah well. I'll let _you_ chase it down I guess.

You're good at that.&nbsp;`:)`

**Comment by ivan-w** [comment]
For info.. The problem is not in DMKSCNSD ! It's in DMKCSP - which has a call to TRT to validate the class given in CP SPOOL is valid.

Now looking at the code, I found another problem : Part of the optimization breaks TRT (but that's not the issue here)... You can't copy the 1st and 2nd operands before hand ! The PoP (at least z/Arch PoP) says : 

`Access exceptions are recognized only for those
bytes in the second operand which are actually
required. Access exceptions are not recognized for
those bytes in the first operand which are to the right
of the first byte for which a nonzero function byte is
obtained.

(So basically - yes - you are suppose to access BYTE by BYTE - which is why TRT is inherently slow.... But that's NOT the problem at hand) (and there are solutions to make this PoP compliant - and keep the optimisation - basically copy IFF the areas do not cross page boundaries - which would be 99% of the cases)

Otherwise, I think I found the actual problem !

There should be a len++ somewhere (operand 1 length is coded as the length -1 in storage!)..

I'll try that and let you know how it fares !

**Comment by ivan-w** [comment]
Ok... Here are the latest results !
Sample code (run under VM/CMS)
```
TRT1     CSECT *
         STM   14,12,12(13)
         BALR  12,0
         USING *,12
         LA    3,A1
         LA    4,A2
         TRT   0(1,3),0(4)
         BALR  5,0
         SRL   5,28
         N     5,=XL4'3'
         LINEDIT TEXT='CC=.....',SUB=(DEC,(5))
         LM    14,12,12(13)
         XR    15,15
         BR    14
         DS    0D
A1       DC    C'A'
A2       DC    XL256'0'
         ORG   A2+X'C1'
         DC    C'A'
         ORG   A2+256
         DS    0D
         LTORG
         END
```
When running under the current code : 
```
 load trt1 ( start            
DMSLIO740I Execution begins...
CC=1.                         
```
When running on an actual IBM 4361 : 
```
 load trt1 ( start         
Execution begins...        
CC=2.                      

```
It's probably a very simple problem !

**Comment by ivan-w** [comment]
Got it ! 
Please apply the following : 
```
diff --git a/general2.c b/general2.c
index e599651c..a0e5562e 100644
--- a/general2.c
+++ b/general2.c
@@ -1701,16 +1701,17 @@ BYTE    dbyte = 0, sbyte = 0;           /* Byte work areas           */
     ARCH_DEP( vfetchc )( op2, 256-1, addr2, b2, regs );

     /* Process first operand from left to right */
-    for (i=0; i <= len && sbyte == 0; i++)
+    for (i=0; i <= len ; i++)
     {
         dbyte = op1[i];
         sbyte = op2[ dbyte ];
+       if(sbyte) break;
     }

     /* Test for non-zero function byte */
     if (sbyte != 0)
     {
-        addr1 += i - 1;
+        addr1 += i;
         addr1 &= ADDRESS_MAXWRAP( regs );

         /* Store address of argument byte in register 1 */

```
The problem was that... The 2rd argument of the for statement is applied BEFORE the test - so i was off by one.. Which was fine for the addr (with the -1) computation but wrong for the CC ! It's more simple to break out of the loop when the function byte is non 0 which ensure 'i' is correct at this point.

We still have to address the PoP compliance of TRT (regarding access exceptions, but I'll open another issue for that)

**Comment by Fish-Git** [comment]
> but wrong for the CC! It's more simple to break out of the loop when the function byte is non 0 which ensures 'i' is correct at this point.

Well... In _my_ opinion it would have been easier to simply adjust the 'cc' statement:
```
- cc = (i == len) ? 2 : 1;
+ cc = ((i-1) == len) ? 2 : 1;
```
But to each their own I guess. &lt;shrug&gt;

What's weird though (and I'm _definitely_ going to have to look into this and get back to you), is my "CLCL-et-al" runtest integrity test is already testing for proper condition code handling, and it passes! (I already have a test that tests for CC2)

I'll have to look into this further...

**Comment by Fish-Git** [comment]
I'm going to go ahead and close this issue since its resolution is included in the resolution for Issue #108.

(Thanks for your help on this one, Ivan! _MUCH_ appreciated, buddy!)

**Comment by ivan-w** [comment]
No sweat ! We're all on this together ;)

**Comment by Fish-Git** [comment]
> What's weird though (and I'm definitely going to have to look into this and get back to you), is my "CLCL-et-al" runtest integrity test is already testing for proper condition code handling, and it passes!   (I already have a test that tests for proper CC2!)
> 
> I'll definitely have to look into this more deeply. I might have a bug in my test case.
> 
> Let me look into it and get back to you...

FYI: My test case _did_ have a bug in it that was causing it to _never_ detect wrong condition codes! The bug has since been fixed of course and your new TRT code passes just fine.
