### ISSUE TITLE
TRT not compliant with PoP rules regarding access exceptions

### ISSUE THREAD

**Issue by ivan-w** [Fish-Git/hyperion#108]
>Access exceptions are recognized only for those
bytes in the second operand which are actually
required. Access exceptions are not recognized for
those bytes in the first operand which are to the right
of the first byte for which a nonzero function byte is
obtained.

However, the current code will generate an access exception if any of the operands cross a page boundary and the next page isn't accessible because the optimized TRT code pre-fetches both operands. Pre-fetch should _only_ be performed when operands do not cross page boundaries. Otherwise a byte by byte fetch should be performed.

Fish, please assign this one to me.&nbsp;`;)`

--Ivan

**Comment by ivan-w** [comment]
Please find herein a patch that addresses both #107 and #108 : 
```
diff --git a/general2.c b/general2.c
index e599651c..a644d9e6 100644
--- a/general2.c
+++ b/general2.c
@@ -1691,26 +1691,78 @@ int     len;                            /* Length - 1                */
 int     i;                              /* work variable             */
 int     cc = 0;                         /* Condition code            */
 BYTE    dbyte = 0, sbyte = 0;           /* Byte work areas           */
+int    op1cpb;                         /* Operand 1 crosses Page Bdy*/
+int    op2cpb;                         /* Operand 2 crosses Page Bdy*/

     SS_L( inst, regs, len, b1, addr1, b2, addr2 );

-    /* Copy operand-1 data to work area */
-    ARCH_DEP( vfetchc )( op1, len, addr1, b1, regs );
+    op1cpb=((addr1 & PAGEFRAME_PAGEMASK) != ((addr1+len+1) & PAGEFRAME_PAGEMASK));
+    op2cpb=((addr2 & PAGEFRAME_PAGEMASK) != ((addr2+256) & PAGEFRAME_PAGEMASK));

-    /* Copy operand-2 data to work area */
-    ARCH_DEP( vfetchc )( op2, 256-1, addr2, b2, regs );
+    /* Copy operand-1 data to work area if within same page */
+    if(!op1cpb)
+    {
+        ARCH_DEP( vfetchc )( op1, len, addr1, b1, regs );
+    }
+
+    /* Copy operand-2 data to work area if within same page */
+    if(!op2cpb)
+    {
+        ARCH_DEP( vfetchc )( op2, 256-1, addr2, b2, regs );
+    }

     /* Process first operand from left to right */
-    for (i=0; i <= len && sbyte == 0; i++)
+    if(unlikely(op1cpb))
     {
-        dbyte = op1[i];
-        sbyte = op2[ dbyte ];
+        if(unlikely(op2cpb))
+        {
+            /* Both operands cross a page boundary */
+            for(i=0;i<=len;i++)
+            {
+                dbyte = ARCH_DEP(vfetchb)(addr1+i,b1,regs);
+                sbyte = ARCH_DEP(vfetchb)(addr2+dbyte,b2,regs);
+               if(sbyte) break;
+            }
+        }
+        else
+        {
+            /* Operand 1 crosses a page boundary */
+            for(i=0;i<=len;i++)
+            {
+                dbyte = ARCH_DEP(vfetchb)(addr1+i,b1,regs);
+                sbyte = op2[dbyte];
+               if(sbyte) break;
+            }
+        }
+    }
+    else
+    {
+       if(unlikely(op2cpb))
+       {
+            /* Operand 2 crosses a page boundary */
+            for(i=0;i<=len;i++)
+            {
+                dbyte = op1[i];
+                sbyte = ARCH_DEP(vfetchb)(addr2+dbyte,b2,regs);
+               if(sbyte) break;
+            }
+       }
+       else
+       {
+            /* neither operands cross a page boundary */
+            for(i=0;i<=len;i++)
+            {
+               dbyte = op1[i];
+               sbyte = op2[dbyte];
+              if(sbyte) break;
+            }
+       }
     }

     /* Test for non-zero function byte */
     if (sbyte != 0)
     {
-        addr1 += i - 1;
+        addr1 += i;
         addr1 &= ADDRESS_MAXWRAP( regs );

         /* Store address of argument byte in register 1 */

```
You may need to address tabs, formatting & whatnot ;)

Please apply any test suite you deem necessary !

--Ivan

**Comment by Fish-Git** [comment]
> Please find herein a patch that addresses both #107 and #108:

_Thank you_, Ivan! You're a pal.&nbsp;`:)`

&nbsp;

> You may need to address tabs, formatting & whatnot.&nbsp;`;)`

Of course.&nbsp;`;-)`

&nbsp;


> Please apply any test suite you deem necessary!

Definitely!

**Comment by ivan-w** [comment]
Making a test case a tricky.. You need to check for the cases where the page is crossed but not ACTUALLY used !

**Comment by Fish-Git** [comment]
FYI: I haven't forgotten about you, Ivan! I've just been busy trying to resolve some other issues at the same time (#102 and #106). I want to get them out of the way first, so I can concentrate my full attention on your (this) issue.

**Comment by ivan-w** [comment]
Don't fret ! I think the patch is sane (been running it for a bit now and it solved my problem !)
Review and Apply the changes whenever you get a chance and create the test case at our convenience !
--Ivan

**Comment by Fish-Git** [comment]
Committed!&nbsp;&nbsp;Issue closed.

Thanks for all of your help on this one, Ivan.

_Much_ appreciated, buddy.

**Comment by Fish-Git** [comment]
Now all I have to do is try to apply the same technique to the MVCIN instruction! (which I unfortunately farqed up the same way)

**Comment by ivan-w** [comment]
You don't have to worry about crossing pages with MVCIN ! Contrary to TRT, not only are both operands the same size, but there is nothing that prevents both operands to be processed in their entirety (besides an access exception). The tricky part here was about TRT is that depending on storage contents, there were possibilities for access exception to NOT occur even if portions of either (or both) operands were inaccessible !

**Comment by ivan-w** [comment]
For MVCIN, the *only* issue that might arise is the *ORDER* in which access exceptions are recognized (which could have an importance in case of a Translation Exception) - but there isn't anything in the PoP that states that the access order is of any importance. If you use a local cache (block vfetchc/vstorec) for both operands, the access exception will occur anyway, just not in the same order than if you do a bunch of vfetchb/vstoreb ! So I wouldn't worry about that !

**Comment by Fish-Git** [comment]
**THANK YOU!**

I've been tearing my hair out trying to figure out how to ensure the access exceptions occur in the proper order (_as-if_ the operands were processed one byte at a time but _without_ actually processing them that way).

If, as you say, the order doesn't actually matter, then you're right! It's fine as-is! (which makes me _very_ happy!)

Thanks, Ivan!&nbsp;`:-D`

**Comment by ivan-w** [comment]
Using the same technique as with TRT for MVCIN (check page crossing boundaries, etc).. can easily make it appear as if we're treating one byte at a time (I guess.. Haven't looked at the code really)... I also need to look at TRTR, TRTE and TRTRE... Those guys may also need some adjustment... I'll look at those later on ! Right now I need some shuteye (it's 6AM here).
--Ivan

**Comment by Fish-Git** [comment]
> Please apply any test suite you deem necessary!

FYI: my test case ("CLCL-et-al") (which tests the CLCL, MVCIN and TRT instructions) had a cc bug in its TRT test that was causing it to never detect wrong condition codes. The bug has since been fixed and your new TRT code now passes just fine.

**Comment by ivan-w** [comment]
That is great news :) Thanks for taking the time and effort for this !

**Comment by ivan-w** [comment]
Are we going to need a test suite for test suites ? Ah ah - Just kidding !

**Comment by Fish-Git** [comment]
> I also need to look at TRTR, TRTE and TRTRE. Those guys may also need some adjustment. I'll look at those later on.

I would appreciate that _very_ much, Ivan!

Since you're volunteering I'll go ahead and temporarily assign this issue to you and mark it "In Progress..."

**Comment by Fish-Git** [comment]
> ... I'll go ahead and temporarily assign Issue #101 to you ...

(Dang!) Apparently I can't do that until you first _reply_ (post a comment to) Issue #101 first!&nbsp;`:(`

**Comment by Fish-Git** [comment]
> I also need to look at TRTR, TRTE and TRTRE. Those guys may also need some adjustment. I'll look at those later on.
> 
> Since you're volunteering, I'll go ahead and temporarily assign Issue #101 to you and mark it "In Progress..."

> (Dang!) Apparently I can't do that until you first reply (post a comment to) Issue #101 first! :(

The above is no longer true now that @ivan-w is now a member of our organization, so I've gone ahead and assigned issue #101 to Ivan.

Ivan? If this is unacceptable, then please feel free to remove yourself as the assignee!
