### ISSUE TITLE
XCF signaling stopped working with ga36e0bbc

### ISSUE THREAD

**Issue by edtgek** [Fish-Git/hyperion#11]
Hi. After installing Hercules pre-built version Hercules-4.0.0.8873-SDL-ga36e0bbc, XCF signaling stopped working in both my base sysplex.

With version Hercules-4.0.0.8845-SDL-g15c01ddb and some earlier versions both my base sysplex is working great.

I tested the newest version a couple of times and the first system in the plex is coming up fine but the second system get no contact with the first system. This happens every time I test. You can see the response in the last picture in the attached file. As soon I go back to the version Hercules-4.0.0.8845-SDL-g15c01ddb both my plex works fine again.

In the attached file I show how the CTCE's are configured in the two Hercules configuration files as well as the corresponding parmlib couple members for both systems.

[XCF_signalling_stopped_working.docx](https://github.com/Fish-Git/hyperion/files/1169007/XCF_signalling_stopped_working.docx)

**Comment by Fish-Git** [comment]
@edtgek : I am not familiar with sysplex and admit I have never tried to create on using CTCE.

I would like to try and recreate the problem for myself so that I can properly debug this issue.

What are the requirements? Do I simply define two Herc systems using cross-connected CTCE devices like you have, along with `PARMLIB(COUPLE)` members (with swapped `PATHIN` and `PATHOUT` statements) like you have? Is that all there is to it?

Thanks.

(And sorry about the breakage! With your help I'm sure I'll get it fixed!)

**Comment by edtgek** [comment]
Hi.

You can try to test.

You will need 2 CTC addresses in MVS that correspond with the CTCE in the
Herc configuration.

In parmlib in your ieasysxx member you will need the PLEXCFG parameter to be
set to MULTISYSTEM.

You also will need some couple dataset that you see in the couple member.

 

In the Herc configuration the LPARNAME and LPARNUM to be set.


Especially LPARNUM is 1 for the first system and 2 for the second.

 

It might be more things but test to see if you can bring up the first system
and then see what happened with the second.

 

Göran Eklöf

 

Sjödalsvägen 26

141 47 Huddinge

Sweden

**Comment by Fish-Git** [comment]
> You will need 2 CTC addresses in MVS that correspond with the CTCE in the Herc configuration.

I presume you mean I should use CTC devices in each system's TCPIP PROFILE, each defined with a different IP address, yes? (i.e. a total of 4 different IP addresses? Two for each system (one IP address for each CTC device?)) Is that correct?

> You also will need some couple datasets that you see in the couple member.

How do I create these datasets?

**Note!** &nbsp; I am _very_ inexperienced with MVS/ZOS, so I will need lots of help from you! Thanks!

**Comment by edtgek** [comment]
No, TCPIP is not involved.

To look at this problem I believe you will not even have to start any JES.

 

You will need an IODF file which is the configuration of MVS, which devices
the MVS system should be aware of and there you will need to have 2 CTC
devices.

It should  be 2 CTC devices known to MVS and as defined in the couple
members also known to XCF.

 

In my couple members I am using E24 and E25 they are known to MVS and XCF
and they are also defined in the HERC configuration file as CTCE as I showed
in the file first attached.

A sysplex is 2 or more MVS system that work closely together and they are
using couple datasets to communicate with each other.

I think your couple members can look like below, I think it is the only
couple dataset you will need.

 

I used this JCL to create the couple dataset.

**Comment by Fish-Git** [comment]
@edtgek : Göran,

It sounds like trying to recreate this problem might be beyond my abilities, so I would like to do something else instead.

I would like you to try my test Hercules containing my proposed (possible) fix. Please send me your email address. My email address is fish at softdevlabs dot com.

Thanks!

**Comment by Fish-Git** [comment]
Göran (and any other interested parties):

SDL Hyperion commit 71d9a74804a79d544b7b67d37093177c07b09255 fixes this problem.

Those building Hercules for themselves will simply need to do a git pull to pick up the change and then rebuild Hercules.

Those using pre-built Windows binaries will unfortunately have to wait for the next snapshot, which is more than likely still several weeks away yet.
