### ISSUE TITLE
Hyperion build fails on Mac (BSD)

### ISSUE THREAD

**Issue by swhobbit** [Fish-Git/hyperion#114]
Fresh build of hyperion on Mac High Sierra:
```
Making all in .
  CC     hsys.lo
  CCLD   libhercs.la
  CC     codepage.lo
  CC     hdl.lo
  CC     hexdumpe.lo
  CC     hostinfo.lo
  CC     hscutl.lo
hscutl.c:1639:35: error: too many arguments to function call, expected 1, have 2
    rc = pthread_setname_np( tid, threadname );
         ~~~~~~~~~~~~~~~~~~       ^~~~~~~~~~
/usr/include/pthread.h:499:1: note: 'pthread_setname_np' declared here
__API_AVAILABLE(macos(10.6), ios(3.2))
^
/usr/include/Availability.h:415:126: note: expanded from macro '__API_AVAILABLE'
  ...__API_AVAILABLE4, __API_AVAILABLE3, __API_AVAILABLE2, __API_AVAILABLE1)(__VA_ARGS__)
                                         ^
```
&nbsp;

Manual page for the function:

```
PTHREAD_SETNAME_NP(3)    BSD Library Functions Manual    PTHREAD_SETNAME_NP(3)

NAME
     pthread_setname_np -- set the thread name

SYNOPSIS
     #include <pthread.h>

     void
     pthread_setname_np(const char *name);

DESCRIPTION
     The pthread_set_name_np() function sets the internal name for the calling thread to
     string value specified by name argument.

AUTHORS
     This manual page was written by Alexey Zelkin <phantom@FreeBSD.org>.

BSD                            February 13, 2003                           BSD
```

**Comment by racfra2** [comment]
It would be so nice to obtain pre-built OSX binaries again as in the older days

**Comment by Fish-Git** [comment]
@swhobbit : commit e5c673c918330b6dab0b762a117f55f7bb4c2088 should hopefully fix this issue. Please confirm.

**Comment by Fish-Git** [comment]
@swhobbit : _**OOPS!**_Hang on a second! I forgot to commit the new `configure` script, etc! (_Doh!_)

**Comment by Fish-Git** [comment]
@swhobbit : New `configure` script et al. added! (commit 6d77df6c4a7545aabb53b04f38b5f169e5d4c98c)

Please re-configure and re-make and report back whether this issue is now resolved.

Thanks!

**Comment by Fish-Git** [comment]
> Prematurely closed:
```
Undefined symbols for architecture x86_64:
  "_decnumber_version", referenced from:
      _display_extpkg_vers in version.o
  "_softfloat_version", referenced from:
      _display_extpkg_vers in version.o
  "_telnet_version", referenced from:
      _display_extpkg_vers in version.o
```

Oh...

Well hell, Drew! That's a different problem altogether!

I was asking about the _original_ reported problem:

```
hscutl.c:1639:35: error: too many arguments to function call, expected 1, have 2
    rc = pthread_setname_np( tid, threadname );
         ~~~~~~~~~~~~~~~~~~       ^~~~~~~~~~
```

&nbsp;
which I take it _has_ now been fixed, yes? If so, then I shall certainly start working on addressing this new problem. I know SDL Hyperion has problems building on Mac (someone else reported it to me offline; I just haven't had time to work on it myself since it involves installing a hot copy of OSX inside a hacked virtual machine, which I haven't had time to do yet).

Let me see what's going on elsewhere and I'll start working on this new problem as soon as I can and let you know when you can give it another try.

Cool?

**Comment by swhobbit** [comment]
btw, it's all one problem to me in the sense ifa  change happens and the built (still) blows up, I'm not even sure if it made it past the previous error.   Sorry.

**Comment by Fish-Git** [comment]
> BTW, it's all one problem to me in the sense if a change happens and the build still blows up, I'm not even sure if it made it past the previous error. Sorry.

Understood.

But in this case I'm pretty sure we did (make it past the previous error). The previous error was a an error detected by the compiler. This new error is an error detected by the _linker_. I.e. the build got past the compile stage (everything compiled cleanly) and not it's trying to link everything together (all of the various pieces of object code) into the executable, etc, but it's not finding some of it.

The "Undefined symbols" errors you're getting are each for one of the ["External Packages" that SDL Hyperion now links with](https://fish-git.github.io/html/hercrnot.html). The _default_ static link libraries distributed in the source code repository were all built on my CentOS 6.10 virtual machine. It's very likely that they are, for whatever reason, incompatible with your particular flavor of *Nix (or gcc, etc).

To resolve the situation, you simply need to build your own version of each of the External Packages and point your `LIB` environment variable to where they were installed to.

This is a _ONE TIME_ procedure and is explained in the SDL Hyperion "[README.EXTPKG](https://github.com/fish-git/hyperion/blob/master/README.EXTPKG)" document included in the source code distribution.

Please build the affected external packages for your system and then try your Hercules build again. Hopefully it will work better this time.

Thanks.

**Comment by swhobbit** [comment]
> This is a ONE TIME procedure and is explained in the SDL Hyperion "README.EXTPKG" document included in the source code distribution.

```
[frederica:0,~/src/hyperion,03:49:26,25] ls README*
README.AIX		README.HAO		README.MSVC		README.SETUID
README.APL360		README.HDL		README.NETWORKING	README.SUN
README.BSD		README.HERCLOGO		README.OSX		README.TAPE
README.CMPSC		README.HQA		README.PTT		README.WIN64
README.COMMADPT		README.HRAF		README.REXX		README.md
README.DYNMOD		README.IOARCH		README.RUNTEST
README.ECPSVM		README.ISSUES		README.RXVT4APL
README.EXTPKG		README.MINGW		README.S37X
[frederica:0,~/src/hyperion,03:51:31,26] ls README* | wc -l
      29
```
If a project has 29 read me files, the first file read is README.NOW / README.1st / README.md assuming it's directory to rest.  I read the README.md, and stopped when it didn't point me any where else.  

You might cut a bug to reorganize them into a directory of all *.md files with an index (with live links) in a single file at the top level.

**Comment by Fish-Git** [comment]
> If a project has 29 read me files, the first file read is README.NOW / README.1st / README.md assuming it's a directory to the rest. I read the README.md, and stopped when it didn't point me any where else.
> 
> You might cut a bug to reorganize them into a directory of all *.md files with an index (with live links) in a single file at the top level.

It's on my TODO list. I'll get around to it eventually. (There's a _lot_ of things in Hercules that needs cleaning up, but I can only work so fast. I may be a Herculean but I'm certainly not the mythical character himself!)

**Comment by swhobbit** [comment]
I am unsure why Hercules was split into five packages, but such complications provide a sufficient additional load that seemingly my simple quest to use the LCS support has already consumed too much of my time.  I'm closing my remaining issues and dropping all attempts to use Hyperion.

**Comment by Fish-Git** [comment]
> ... my simple quest to use the LCS support ...

(Huh?) Hercules has _always_ supported LCS devices! Even _before_ Hyperion came along!

Have you tried building the ["other" Hyperion](http://hercules-390.github.io/html/)? Perhaps you'll have better luck with it?

**Comment by Fish-Git** [comment]
FYI:

> You might cut a bug to reorganize them into a directory of all *.md files with an index (with live links) in a single file at the top level.

Done! GitHub Issue #117 created.

**Comment by Fish-Git** [comment]
Fish note: This issue is related to issue [#84: "SDL-hyperion Build Failure on MacOS"](https://github.com/Fish-Git/hyperion/issues/84)
