### ISSUE TITLE
Limit in FBA volume sizes

### ISSUE THREAD

**Issue by hugolia** [Fish-Git/hyperion#12]
I have running into problem when I try to use FBA volumes larger than 3GB.
I can attach the volume to the guest machine but when I try to format the volume using ICKDSF it gives errors above block 799994 4K blocks (6399952 512B blocks).
Tried different FBA type devices with same results.
I used CKD devices larger than 3GB without problems, it seems that this limit only accurs on FBA devices.

ICK30701I  EQUIPMENT CHECK ON D001
CSW = D87B60 0E000000   CCW = 41DE33E8 20000006   FILEMASK = C4
SENSE = 10000000 00000000 00000000 00000000 00000000 00000000
ICK30699I I/O RETRY LIMIT EXCEEDED
ICK10710I I/O ERROR OCCURRED ON DEVICE D001
CSW = D87B60 0E000000   CCW = 41DE33E8 20000006   FILEMASK = C4
SENSE = 10000000 00000000 00000000 00000000 00000000 00000000

**Comment by Fish-Git** [comment]
The supported FBA dasd device types and their corresponding sizes are:
```
                            FBA DEVICES

            BYTES/  BLOCKS/  BLOCKS/   BLOCKS/    BYTES/
DISK TYPE   BLOCK   TRACK    CYLINDER  ACTUATOR   ACTUATOR

3310         512      32       352     125,664    64,339,968
3370-Al/B1   512      62       744     558,000   285,696,000
3370-A2/B2   512      62       744     712,752   364,929,024
9313-1/14    512      96       480     246,240   126,074,880
9332-200     512      73       292     360,036   184,338,432
9332-400     512      73       292     360,036   184,338,432
9332-600     512      73       292     554,800   284,057,600
9335         512      71       426     804,714   412,013,568
9336-10      512      63       315     920,115   471,098,880
9336-20/25   512     111       777   1,672,881   856,515,072
0671         512      63       504     574,560   294,174,720
0671-04      512      63       504     624,456   319,721,472
0671-08      512      63       504     513,072   262,692,864
```

As you can see none of the supported FBA dasd device types support any size larger than 865MB, nor am I aware of _any_ FBA device type that supports a 3GB device size.

**Comment by hugolia** [comment]
If you specify the number of blocks in the dasdinit program you can create volumes with higher sizes; even you can create CKD volumes higher than 3390-9 specifying the number of cylinders. Those bigger volumes can be attached and are managed fine with Hercules. 
I am running Hercules with z/VM 6.3.0 for educational purposes, and using 30GB CKD volumes without problem.

I've found a workaround using volumes created with 20,971,584 blocks, that are a little more than 10GiB. See: [https://groups.yahoo.com/neo/groups/H390-VM/conversations/topics/12704](url)
