### ISSUE TITLE
Problem compiling on platforms which have inttypes.h but don't have stdint.h

### ISSUE THREAD

**Issue by PeterCoghlan** [Fish-Git/hyperion#6]
When trying to compile on VMS, I get conflicts between the following typedefs in htypes.h and variants  of the same typedefs in inttypes.h which is included if available before them:

typedef char                  int8_t;
typedef long long          int64_t;
typedef unsigned long long    uint64_t;

It appears that this can be resolved using something like the following:

#ifdef HAVE_INTTYPES_H
  #include <inttypes.h>
#elif defined(HAVE_STDINT_H)
  #include <stdint.h>
#else
  list of several typedefs for those who have neither inttypes.h nor stdint.h
#endif

At least that works for me.  It probably should be tested on other platforms too.

**Comment by PeterCoghlan** [comment]
There seems to be a similar issue with typedefs in decnumber/include/deccontext.h where a check is also made for whether stdint.h is available but not for inttypes.h

**Comment by Fish-Git** [comment]
Fixed in commit bd048b751b7304f4a1c0690ba36e3d9e2e1dd57e

**Comment by PeterCoghlan** [comment]
Many thanks Fish.  It works now without any conflicting typedefs.
