### ISSUE TITLE
Problem compiling with NO_IEEE_SUPPORT defined

### ISSUE THREAD

**Issue by PeterCoghlan** [Fish-Git/hyperion#7]
When I try to compile with NO_IEEE_SUPPORT defined, compiling some modules (config.c for example) fails with:

%CC-E-ERRORMESSAGE, #error Floating point extension facility requires binary floating point
at line number 629 in file HERCULES_CODE:[FISH-2017-02-07]FEATCHK.H;1

It appears that this has been worked around historically in hyperion by commenting out

#define FEATURE_FLOATING_POINT_EXTENSION_FACILITY

in feat900.h, however this no longer done in this fork.

**Comment by Fish-Git** [comment]
> %CC-E-ERRORMESSAGE, #error Floating point extension facility requires binary floating point
at line number 629 in file HERCULES_CODE:[FISH-2017-02-07]FEATCHK.H;1

What the heck compiler are you using? I've never such a confusing, unusually formatted error message before in my life!

**Comment by PeterCoghlan** [comment]
$ cc /version
HP C V7.1-015 on OpenVMS Alpha V8.3

The error message might seem unusual but it is anything but confusing, to me anyway. The part up to the comma is a standard VMS message. It identifies the entity which issued the message (CC), the severity (E for error, as opposed to informational, warning, success or fatal error) and gives the unique short form of this particular message (ERRORMESSAGE).   It is quite similar to VM standard messages except that VM uses numbers to differentiate between messages instead of the short form of the message. It is possible to look up the message from the short form and get the following:

CC

  Messages

    ERRORMESSAGE


      Message        #error<errormsg>

      Description    An #error directive was encountered.  This message
                     will include the text that follows the directive in
                     the source program.
  
So the error message is saying the directive:

#error Floating point extension facility requires binary floating point

was found at line number 629 in featchk.h.

**Comment by Fish-Git** [comment]
Fixed in commit 4a72ca421ebf585c4040635caee54f4f3d892162

**Comment by PeterCoghlan** [comment]
Many thanks Fish.  Compiling with NO_IEEE_SUPPORT defined works for me now with no issues.
