### ISSUE TITLE
Crash: hdt3088.so: undefined symbol: MACTabAdd

### ISSUE THREAD

**Issue by apple601601601** [Fish-Git/hyperion#75]
I got following error message when I changed my TCPPARMS and restarted TCPIP on z/OS running on Hyperion:

`local/bin/hercules: symbol lookup error: /usr/local/lib/hercules/hdt3088.so: undefined symbol: MACTabAdd`

Here are the details:

related config:
```
0E20-0E21 CTCI 192.168.1.100 192.168.1.1
0E40-0E41 LCS
```
There is a line of error flashed very quickly when hercules starts after I added those lines above into my config:

`HHC00136E Error in function execlp(): No such file or directory`

And I found the tun0 interface is setup but with no IP address or netmasks assigned (is the previous error HHC00136E responsible for the IP settings?) so I assigned them manually:

`sudo ifconfig tun0 192.168.1.100 pointopoint 192.168.1.1`

Then I did an IPL as usual, modified my TCPPARMS as following:
```                               
DEVICE CTCDEV1 CTC E20           
LINK CTCLINK1 CTC 0 CTCDEV1                                       
HOME                                
192.168.1.100     CTCLINK1       
BEGINRoutes                                                                
ROUTE 192.168.1.0     255.255.255.0   =  CTCLINK1  MTU  1492               
ROUTE DEFAULT         192.168.1.1        CTCLINK1 MTU  DEFAULTSIZE         
ENDRoutes                                                                                                               
START CTCDEV1                                        

DEVICE LCSDEV1 LCS E40 AUTORESTART                       
LINK LCSLINK1 ETHERNET 0 LCSDEV1                         
HOME                                                     
192.168.1.110 LCSLINK1                                   
BEGINROUTES                                              
ROUTE 192.168.1.0 255.255.255.0 = LCSLINK1 MTU 1492      
ROUTE DEFAULT 192.168.1.1 LCSLINK1 MTU 1492              
ENDROUTES                                                
START LCSDEV1                                            
```
Then I stopped TCPIP and restarted it and just after issuing the start command, hercules crashes with the following error:

`local/bin/hercules: symbol lookup error: /usr/local/lib/hercules/hdt3088.so: undefined symbol: MACTabAdd`

Hercules version:
```
HHC01413I Hercules version 4.0.0.8922-SDL-gc0f9a10 (4.0.0.8922)
HHC01414I (C) Copyright 1999-2017 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Dec 10 2017 at 09:23:57
HHC01417I Built with: GCC 4.8.5 20150623 (Red Hat 4.8.5-16)
HHC01417I Build type: GNU/Linux x86_64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 128
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    SIGABEND handler
HHC01417I Without CCKD BZIP2 support
HHC01417I Without HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 hatomics=atomicIntrinsics
HHC01417I Running on: CENTOS (Linux-3.10.0-514.26.2.el7.x86_64 x86_64) MP=28
HHC01417I Built with decNumber external package version 3.68.0.65-g16013c6
HHC01417I Built with SoftFloat external package version 3.1.0.66-g8e258f8
HHC01417I Built with telnet external package version 1.0.0.27-g4e7798e
HHC00150I Crypto module loaded (c) Copyright 2003-2016 by Bernard van der Helm
HHC01417I Built with crypto external package version 1.0.0.12-gc3f9343
HHC00151I Activated facility: Message Security Assist
HHC00151I Activated facility: Message Security Assist Extension 1, 2, 3 and 4
HHC00100I Thread id 00007f58e7119700, prio 2147483647, name Processor CP00 started
HHC00100I Thread id 00007f58e7018700, prio 2147483647, name Timer started
HHC00811I Processor CP00: architecture mode z/Arch
HHC00100I Thread id 00007f58ea285740, prio 2147483647, name Control panel started
```

**Comment by Fish-Git** [comment]
Thank you for reporting this.

I am looking into this and let you know when it is fixed.

Thanks.

**Comment by Fish-Git** [comment]
1. Please post your _**complete**_ log file, all the way to the crash.

2. Does message `HHC00921I` appear in your log file? &nbsp; Which does it say:
&nbsp;
"_manual_ Multicast assist enabled"?
"_tuntap_ Multicast assist enabled"?

Thanks.

**Comment by Fish-Git** [comment]
I am unable to reproduce your problem.

What happens when you do the following?

  * start Hercules
  * enter the command `lsmod`
  * enter the command `rmmod hdt3088`
  * enter the command `lsmod`
  * enter the command `ldmod hdt3088`
  * enter the command `lsmod`

Does Hercules crash when the `hdt3088` nodule is loaded after being unloaded?

Were there any unexpected/unusual errors or warnings when you built you Hercules? `(*)`

Are you sure you PATH is defined correctly?

Perhaps the `hdt3088` module you are loading is from some _other_ version of Hercules?

Do you have multiple different versions of Hercules installed?

Did you install Hercules after building it, or are you running it from within the build directory itself?
___
`(*)` _Other_ than the usual:
```
    *** Warning: Linking the shared library xxxx against the
    *** static library xxxx is not portable!
```
which are considered to be _completely normal_.

**Comment by apple601601601** [comment]
1. complete log attached named `hyperion_crash.log`.
2. "manual Multicast assist enabled" and "tuntap Multicast assist enabled" do appeared in the log
3. I did the lsmod/rmmod hdt3088/lsmod/ldmod hdt3088/lsmod by starting hercules with and without my config file and it didn't crash in either situation, logs attached named `hyperion_lsmod_with_config.log` and `hyperion_lsmod_without_config.log`
4. I did a rebuild of hyperion and didn't find any unexpected/unusual errors, logs attached named `make.log` and `make_install.log`
5. my PATH is defined as following:
`declare -x PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/sniffer/.composer/vendor/bin:/home/sniffer/.local/bin:/home/sniffer/bin:/home/sniffer/.composer/vendor/bin:/home/sniffer/.composer/vendor/bin:/home/sniffer/.local/bin:/home/sniffer/bin"`
6. I don't have other version of hercules installed. I also have added this line in my config file to ensure they pickup the correct libs:
`MODPATH /usr/local/lib/hercules `
7. I've installed Hercules(Hyperion) after building it.
8. I did a nm of /usr/local/lib/hercules/hdt3088.so and it shows symbol MACTabAdd as U - undefined. Log attached named `nm.log`

###Logs:###
[hyperion_lsmod_without_config.log](https://github.com/Fish-Git/hyperion/files/1561521/hyperion_lsmod_without_config.log)
[make.log](https://github.com/Fish-Git/hyperion/files/1561522/make.log)
[make_install.log](https://github.com/Fish-Git/hyperion/files/1561523/make_install.log)
[nm.txt](https://github.com/Fish-Git/hyperion/files/1561524/nm.txt)
[PATH.txt](https://github.com/Fish-Git/hyperion/files/1561525/PATH.txt)
[hyperion_crash.log](https://github.com/Fish-Git/hyperion/files/1561526/hyperion_crash.log)
[hyperion_lsmod_with_config.log](https://github.com/Fish-Git/hyperion/files/1561527/hyperion_lsmod_with_config.log)

**Comment by Fish-Git** [comment]
Thanks for the files.  I am going to try the `nm` command on both of my CentOS systems (6.9 and 7.0) on both the build directory's results (./.libs/hdt3088.so) as well as the make install's results (/usr/local/lib/hercules/hdt3088.so) to see if there's any difference.

For what it's worth, my `nm` results on my CentOS 6.9 system shows `MACTabAdd` as defined, not undefined, for both the version of hdt3088.so in the build directory as well as the version in the /usr/local/lib/hercules install directory. I don't understand why yours is undefined.

My kernel and o/s version information (uname -r and cat /etc/centos-release) are reported as follows:

  * kernel versions:
    * Fish (6.9):  2.6.32-696.16.1.el6.x86_64
    * Fish (7.0):  3.10.0-514.26.2.el7.x86_64
  * o/s versions:
    * Fish (6.9):  Description: CentOS release 6.9 (Final)
    * Fish (7.0):  CentOS Linux release 7.3.1611 (Core)

What are the values for _your_ system?

**Comment by apple601601601** [comment]
Thank you for the investigation, my kernal and O/S version as following:
3.10.0-514.26.2.el7.x86_64
CentOS Linux release 7.4.1708 (Core)

At fisrt I guess the problem might comes from the toolchain for build or building parameters so I did a make clean and build again, problem still exists.
However after I removed the source files and did a `git clone` from the scratch, the hdt3088.so has those symbols in there.  Guess I must have messed up the local files somehow. 

Thank you for the diag and sorry for the waste of your time.

**Comment by Fish-Git** [comment]
(Whew!) THANK YOU for letting me know! I was getting worried. The behavior was so weird.

I'm happy that you figured it out and got it working.

Have a happy holiday season! &nbsp; `:)`

**Comment by Fish-Git** [comment]
p.s. How did you get CentOS 7.4?

Mine is only 7.3 and whenever I run System Update, it says there are none!

**Comment by apple601601601** [comment]
Thanks and Merry Christmas! (Though might be a bit earlier :)
I've no idea how I got CentOS 7.4. I do a `yum update` regularly so I guess that's when they update the kernel and sys. I also added some repositories for some software I needed, and that might be the reason.
Here's my repolist:
```
repo id                     repo name                                     status
base/7/x86_64               CentOS-7 - Base - mirrors.aliyun.com           9,591
ce_stable                   ownCloud Server stable Community Edition (Cen      2
epel/x86_64                 Extra Packages for Enterprise Linux 7 - x86_6 12,136
extras/7/x86_64             CentOS-7 - Extras - mirrors.aliyun.com           327
librehat-shadowsocks/x86_64 Copr repo for shadowsocks owned by librehat       51
mongodb                     MongoDB Repository                                279
remi-safe                   Safe Remi's RPM repository for Enterprise Lin  2,578
resilio-sync/x86_64         Resilio Sync x86_64                                1
updates/7/x86_64            CentOS-7 - Updates - mirrors.aliyun.com        1,540
webtatic/x86_64             Webtatic Repository EL7 - x86_64                 546
repolist: 27,051
```
