### ISSUE TITLE
dasdcopy: Fix error propagation in read path.

### ISSUE THREAD

**Issue by Fish-Git** [Fish-Git/hyperion#80]
This is a copy of JP Sugarbroad 's (taralx's) [hercules-390/hyperion issue 241](https://github.com/hercules-390/hyperion/pull/241) of the same name.

He writes:

> This was caught via -Wmisleading-indentation, which unfortunately has a bunch of misfires due to creative indentation style.

Apparenty due to some missing braces in a multiple `if` statement sequence in `dasdcopy.c` incorrect behavior occurs for FBA devices.  His patch adds this missing braces to correct the problem.

**Comment by Fish-Git** [comment]
The patch (merge) that "taralx" (JP Sugarbroad) offers has been committed to my test repository and will be moved into my publicly visible fish-git/hyperion repository and will appear in the next release as soon as I'm finished with what I'm currently working on.

**Comment by Fish-Git** [comment]
Fixed in commit 4ee084f9e958ff5ae88c3ccad8be7500be47ebc5

**Comment by srorso** [comment]
Maybe 69905c9?  (I had a moment and wanted to see what you had done with the PR?  Looks like an easy one to clear.)
