### ISSUE TITLE
HHC02227E Shell/Exec commands are disabled

### ISSUE THREAD

**Issue by erwinmars** [Fish-Git/hyperion#88]
Since version 4.0.0.8873-SDL-ga36e0bbc i get always msg

``` 
HHC02227E Shell/Exec commands are disabled.
```

I start with a RC file. This file starts the WC3270 terminals with a SH command. The file contains:

```
http start
sh $(GUIKWD) start_terms_$(EMULATOR).bat
pause 10
ipl a81
```

GUIKWD contains `STARTGUI`

This has worked fine in versions before 8873 and also in all release 3.

[hercules_64_400-180405-142123.zip](https://github.com/Fish-Git/hyperion/files/1880119/hercules_64_400-180405-142123.zip)

**Comment by Fish-Git** [comment]
This is the new default behavior that was introduced in version 8873 unless overridden by a [`SHCMDOPT`](https://fish-git.github.io/html/hercconf.html#SHCMDOPT) `ENABLE` statement.

I am sorry this caught you by surprise. It was mentioned in the [Release Notes](https://fish-git.github.io/html/hercrnot.html), which should always be reviewed after each new release.
