### ISSUE TITLE
QETH: ipaddr and netmask required in device definition even when using qeth in Layer 2 mode

### ISSUE THREAD

**Issue by ivan-w** [Fish-Git/hyperion#89]
QETH devices currently require the ipaddr and netmask flags/options - even though the QETH device can be used in Layer 2 mode (at which point the QETH device doesn't need an IPV4 address of its own)

**Comment by Fish-Git** [comment]
That's a very good point, Ivan.

I'll take a look at the code and see what I can do.

p.s. I could _really_ use some help with the Linux implementation! I tried to get it to work on my CentOS 6.9 and 7.0 systems, but could never figure it out. Like the tuntap documentation, my Linux networking skills are also virtually non-existent. Any help you and/or Ian can give me (in the form of patches for example?) would be **_greatly_** appreciated!

**Comment by mcisho** [comment]
The requirement for ipaddr and netmask was made Windows only in commit e105faa (2018-04-14).

I suggest that the line requiring netmask, i.e.
  if (!grp->ttnetmask)
should be changed to require netmask or prefix, i.e.
  if (!grp->ttnetmask && !grp->ttpfxlen)

**Comment by Fish-Git** [comment]
Done! Fixed in commit 293a63a38420ebd3b2ce0fdc4a02cf30d7e4b022.

Thanks, Ian!

**Comment by ivan-w** [comment]
I confirm that the issue no longer exists. Thank you all.
