### ISSUE TITLE
Make fails with Makefile:1520: recipe for target 'all' failed.

### ISSUE THREAD

**Issue by rgschmi** [Fish-Git/hyperion#90]
Make fails with the following error.  Makefile:1520: recipe for target 'all' failed.

Zip file was downloaded on 4/13/2018.  Last few lines of make:
....
facility.c:1322:22: warning: unused variable 'eQType' [-Wunused-variable]
Makefile:2048: recipe for target 'facility.lo' failed
make[2]: *** [facility.lo] Error 1
make[2]: Leaving directory '/home/rgschmi/hyperion-master'
Makefile:2098: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rgschmi/hyperion-master'
Makefile:1520: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rgschmi** [comment]
Running openSUSE 43.3

**Comment by Fish-Git** [comment]
Obvious compiler bug. Please upgrade your compiler (gcc or clang or whatever) or report this as a bug in whichever version of whichever compiler you are using.

Anyone who knows 'C' will tell you the variable 'eQType' is _obviously_ referenced! (so the error being report is _completely **bogus**_!)

**Comment by Fish-Git** [comment]
(Oops!) Isee the bug now. Sorry! I'll get it fixed right away.

**Comment by Fish-Git** [comment]
Fixed by commit 8dadc5edb202d696e47e5af09560790f8ab61b8d.
