### ISSUE TITLE
ARCHLVL S/370 MAINSIZE issues

### ISSUE THREAD

**Issue by somitcw** [Fish-Git/hyperion#94]
_(Note: below problem description was edited by Fish)_
.
All System/370 Principles of Operation manuals make clear storage up to 2GB is supported(*), but Hyperion for some reason limits ARCHLVL S370 to 64MB with message HHC01451E:

```
HHC01603I archlvl s370
. . .
HHC01603I mainsize 160
HHC01451E Invalid value 160 specified for MAINSIZE
HHC01441E Config file[46] conf/Turnkey_MVS.conf: error processing statement: MAINSIZE 160
```

A second issue is that the above imposed limit introduces a Hercules configuration file statement sequence issue when attempting to work around the first problem: You need to specify ARCHLVL ESAME _before_ settingMAINSIZE to a value over 64MB, and then switch back to ARCHLVL S/370 afterwards:

```
HHC01603I archlvl esame
. . .
HHC01603I mainsize 160
HHC17003I MAIN     storage is 160M (mainsize); storage is not locked
HHC01603I archlvl s/370
HHC00811I Processor CP00: architecture mode S/370
```
.
Hercules user "Peppe" (Giuseppe Vitillaro) located the root cause of the problem as being the code sequence beginning at line 3156 in source member `hsccmd.c`:

```C
    /* Validate storage sizes by architecture; minimums handled in
     * config.c
     */
    if ( (!mainsize && sysblk.maxcpu > 0) ||    /* 0 only valid if MAXCPU 0           */
         ( sysblk.arch_mode == ARCH_370_IDX &&      /* 64M maximum for S/370 support      */
           mainsize > 0x004000 ) ||             /*     ...                            */
         ( sysblk.arch_mode == ARCH_390_IDX &&      /*  2G maximum for ESA/390 support    */
           mainsize > 0x080000 ) ||             /*     ...                            */
         ( sizeof(size_t) < 8 &&                /*  4G maximum for 32-bit host        */
           mainsize > 0x100000 ) )              /*     addressing                     */
    {
        WRMSG( HHC01451, "E", argv[1], argv[0]);
        return -1;
    }
```

As you can see it is purpose imposing a 64M maximum for S/370. The question is why was this code added? It is clearly wrong.
.
___
(*) [GA22-7000-10 System-370 Principles of Operation](http://www.bitsavers.org/pdf/ibm/370/princOps/GA22-7000-10_370_Principles_of_Operation_Sep87.pdf), [SA22-7085-01 System-370 XA Principles of Operation](http://www.bitsavers.org/pdf/ibm/370/princOps/SA22-7085-1_370-XA_Principles_of_Operation_Jan87.pdf) and [SA22-7200-00 ESA-370 Principles of Operation](http://www.bitsavers.org/pdf/ibm/370/princOps/SA22-7200-0_370-ESA_Principles_of_Operation_Aug88.pdf), pages 11-26, 11-23 and 11-22 respectively, where each mention what value is stored at address 248 (Failing Storage Address) when a storage error Machine Check occurs.

**Comment by somitcw** [comment]
It has been suggested that if a valid MAINSIZE was requested and worked, that there should be a warning.
To me, a response that the MAINSIZE command worked would be more appropriate.

**Comment by Orfheo** [comment]
I agree. What damage may come from a MAINSIZE greater than what actually supported from the target OS? A WARNING isn't more than enough, eventually?

**Comment by Fish-Git** [comment]
Resolved by commit e5c14b1870a67e6002377103d4814e750602cda0.

Changes were made to not only ensure 2G MAINSIZE is allowed/supported for System/370, but a new warning message `HHC17006W` was also introduced to notify the user when storage is automatically increased/decreased to the architectural minimum/maximum whenever a new architecture level is set via the `ARCHLVL` command  and the currently defined MAINSIZE is outside the new architecture's valid range:

```
HHC01603I archlvl z/Arch
HHC02204I ARCHLVL        set to z/Arch
HHC01603I mainsize 3g
HHC17003I MAIN     storage is 3G (mainsize); storage is not locked
HHC01603I archlvl s/370
HHC00811I Processor CP00: architecture mode S/370
HHC02204I ARCHLVL        set to S/370
HHC17006W MAINSIZE decreased to 2G architectural maximim
HHC02204I LPARNUM        set to BASIC
HHC01603I mainsize 64k
HHC17003I MAIN     storage is 64K (mainsize); storage is not locked
HHC01603I archlvl z/Arch
HHC00811I Processor CP00: architecture mode z/Arch
HHC02204I ARCHLVL        set to z/Arch
HHC17006W MAINSIZE increased to 1M architectural minimim
HHC02204I LPARNUM        set to 1
HHC02204I CPUIDFMT       set to 0
```

I presume this now successfully/acceptably resolves this issue.

(Existing testing harness 'mainsize.tst' runtest test was also adjusted and new tests added to account for the new behavior and messages.)

**Comment by somitcw** [comment]
The resolution looks good, but I don't understand a 1MB minimum for zArch.
Is that for an operating system like zOS, zVM, zVSE, or for stand alone utilities?
I don't believe that the 1MB minimum will cause harm?
Does Hercules also require increments of 1MB memory for zArch so we get automatic rounding?

**Comment by Orfheo** [comment]
Yep, tested. I merged to my personal local branch your fix and it works like a charm, at least for MVS3.8j, ARCHMODE S/370, with any order of the statements in the config file.

Thanks so much!
