### ISSUE TITLE
Feature HERC_370_EXTENSION not enabling (or turning into NO-OP) some instructions

### ISSUE THREAD

**Issue by ivan-w** [Fish-Git/hyperion#97]
The instruction enable/disable logic seems to be faulty for instructions that have been targeted by OPTION_OPTINST (notably the A7x4 - Branch Relative on Condition).

Under hyperion, when ldmod s37x is performed, with CC=0, A7840004 will correctly jump over the next 4 bytes (8 bytes after the BRC instruction) in S/370 mode.

Under HSDL, when feature HERC_370_EXTENSION is enabled, with CC=0, A7840004 is no-oped (no branch is taken and the instruction following the branch is executed) in S/370 mode.

I Suspect their could be a conflict between OPTION_OPTINST, the pre-definition of instructions with their mask and the facility.c line: `DIS_FAC_INS( A704, "branch_relative_on_condition" );` - which may only target portions of the instruction interpretation table.

**Comment by ivan-w** [comment]
This may affect all instructions which are targeted by OPTION_OPTINST - I will look into it (I'll have to see if I can figure out the github pull request mechanism and whatnot...)

**Comment by ivan-w** [comment]
Ok.. There is obviously a conflict between the "optimized instruction" option (OPTION_OPTINST) and the "feature" feature... OPTION_OPTINST has an obvious tendency to rewrite the instruction dispatch tables (just like FEATURE does).
I looked around, for HERC_370_EXTENSION (and actually for any feature/facility) the only issue I have is the Branch Relative on Condition instruction (A7x4).
I looked further, and the optimization in this case is REALLY minimal ! It basically shaves off a register shift in certain condition (which is basically free on modern platforms) but also increases the code size (meaning if there are multiple close BRC instructions with different masks, the host will have to take different code path, in effect defeating any Instruction caching and thus leading to a performance degradation).
I therefore recommend and submit for your proposal the removal of OPTION_OPTINST from the BRC/A7x4 code. I have a patch if needed.
--Ivan

**Comment by Fish-Git** [comment]
> This may affect all instructions which are targeted by OPTION_OPTINST - I will look into it...

I would appreciate that very much, Ivan! When I tested I hadn't even thought about the OPTION_OPTINST instructions. I only tested a few of the others which seemed to work fine.

Please _**do**_ let me know whether or not the behavior you discovered applies to all OPTION_OPTINST instructions or not. Thanks!

**Comment by Fish-Git** [comment]
p.s. your fix for this issue was committed (61bdb3b2977d4c359dbbc51e284158d663117603) so I am closing this issue. Thanks again!

**Comment by ivan-w** [comment]
For info.. I looked - and BRC (Branch Relative on Condition) was the only instruction that was both affected by OPTION_OPTINST and which was also affected by the "FEATURE" command modification of the instruction dispatch table (all the other instructions are base instructions that are always available). So we should be good !

**Comment by Fish-Git** [comment]
> So we should be good !

Thanks, Ivan!
